### ISSUE TITLE
Unable to open multiple instances

### ISSUE THREAD

**Issue by AnkitSharma28** [workshare/parallel_pybot#5]
Hi,
Unable to invoke multiple instances, although on cmd screen I'm getting message "max parallel pybots (processes): 5". Only one instance of browser(FF) is appearing, I believe ppybot should invoke multiple browser instance. 

Following are the steps followed:
1) Open the cmd.
2) navigate through cmd, in the drive where ppybot.py & ppybot_config.py are saved.
3) Provide command in cmd to run the execution in parallel along with the folder where testcases exists.
C:\Users\XXXXX\parallel_pybot-master>python ppybot.py D:\XXXX\Automation\Scripts\Test_Suites\Single_Suite

Changes done in "ppybot_config.py".
1) Used the Windows configuration.
2) Changes value for TEST_REGEXP as '.*\Mytest.txt'

Following is the output after running the above stated line in cmd:
Starting bots! Session: main
- source folder: D:\XXXX\Automation\Scripts\Test_Suites\Single_Suite
- results folder: D:\XXXX\Automation\Scripts\Test_Suites\Single_Suite
- max parallel pybots (processes): 5
- max time allowed (seconds): 6000

Please suggest in case I'm doing something wrong here.

Thanks in advance,
Ankit

**Comment by bbossola** [comment]
We are using it all the time, there's no problem in having one of our test opening a browser instance and running it concurrntly with other tests, as each of them will open a separate browser. I cannot find anything wrong in what you are doing.

Would you be able to send a simple script to replicate the issue?

**Comment by bbossola** [comment]
Please see at branch [case#5](https://github.com/workshare/parallel_pybot/tree/case%235) an example containing selenium tests only. Everything is configured (for linux), to launch them just do

`python ppybot . `

You will see the browser opening concurrently during the execution of the tests.

**Comment by AnkitSharma28** [comment]
Thanks for the quick response. Now I got things bit clear, following is my understanding, correct me in case I'm getting incorrect.
Ppybot will run the test cases parallel on the suite level. My scenario was to run test cases from the same suite in parallel instance for that I need to split test cases in different suite. For eg. Initially I had a test suite as "TestSuite" having around 100+ test cases, now to run them parallelly using ppybot.py I had split them in multiple test suite like TestSuite1, TestSuite2, TestSuite3 etc. By this way I am able to run test cases parallel on multiple browser instance.
I hope this is the way it works?

**Comment by bbossola** [comment]
Yes, you are correct. It's quite common to organize the suites in different files, rather than having them into one big file, as this helps to avoid issues when concurrently changing the same file. For example, we in Workshare we have a separate file/suite for each user story, and we run such suites concurrently. We even split most on the in sub-files, separating the frontend tests from the API test and so on

**Comment by bbossola** [comment]
Let me know if you are happy with the outcome so that I can close the issue

**Comment by AnkitSharma28** [comment]
Ya sure... thanks for sharing the info.

**Comment by bbossola** [comment]
No worries, I should I have not assumed :)
